### ISSUE TITLE
编译的时候报错

### ISSUE THREAD

**Issue by zx-code123** [wlgq2/eomaia#2]
刚开始是bind is not a member of std，网上搜了答案加了#include <functional>
![image](https://user-images.githubusercontent.com/33643595/76637087-16745580-6585-11ea-939a-11cd8bbbd3b1.png)
之后编译又有报错  ::readv is not declared
![image](https://user-images.githubusercontent.com/33643595/76637195-41f74000-6585-11ea-999e-865137c72687.png)

**Comment by wlgq2** [comment]
加一个#include <sys/uio.h>就正常了。
我也不知道我之前怎么编译通过的，可能是系统及编译器版本问题。
